CREATE TABLE IF NOT EXISTS api_entries (
    href TEXT PRIMARY KEY,
    title TEXT NOT NULL DEFAULT '',
    short_title TEXT NOT NULL DEFAULT '',
    namespace TEXT NOT NULL DEFAULT '',
    tag TEXT NOT NULL DEFAULT '',
    entry_type TEXT NOT NULL DEFAULT '',
    member_of TEXT NOT NULL DEFAULT '',
    member_of_href TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    folder INTEGER NOT NULL DEFAULT 0,
    is_structural INTEGER NOT NULL DEFAULT 0,
    path TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS api_entry_versions (
    href TEXT NOT NULL REFERENCES api_entries(href),
    version TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'exists',
    content_hash TEXT,
    PRIMARY KEY (href, version)
);

CREATE TABLE IF NOT EXISTS api_version_tree (
    version TEXT NOT NULL,
    href TEXT NOT NULL REFERENCES api_entries(href),
    parent_href TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    depth INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (version, href)
);

CREATE INDEX IF NOT EXISTS idx_version_tree_parent ON api_version_tree(version, parent_href);

CREATE TABLE IF NOT EXISTS api_content (
    href TEXT PRIMARY KEY REFERENCES api_entries(href),
    content_md TEXT,
    fetched_at TEXT,
    fetch_error TEXT
);

CREATE TABLE IF NOT EXISTS api_diffs (
    version_from TEXT NOT NULL,
    version_to TEXT NOT NULL,
    href TEXT NOT NULL,
    diff_type TEXT NOT NULL,
    old_status TEXT,
    new_status TEXT
);

CREATE TABLE IF NOT EXISTS whatsnew_entries (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version TEXT NOT NULL,
    section TEXT NOT NULL DEFAULT '',
    subsection TEXT NOT NULL DEFAULT '',
    title TEXT NOT NULL DEFAULT '',
    content TEXT NOT NULL DEFAULT '',
    content_type TEXT NOT NULL DEFAULT '',
    source TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS code_files (
    id TEXT PRIMARY KEY,
    file_name TEXT NOT NULL DEFAULT '',
    file_path TEXT NOT NULL DEFAULT '',
    summary TEXT NOT NULL DEFAULT '',
    full_code TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS code_entries (
    id TEXT PRIMARY KEY,
    file_name TEXT NOT NULL DEFAULT '',
    file_path TEXT NOT NULL DEFAULT '',
    entry_type TEXT NOT NULL DEFAULT '',
    summary TEXT NOT NULL DEFAULT '',
    content TEXT NOT NULL DEFAULT ''
);
